title: Side Lower
description: Random Ramblings of SB

url: https://sohamlive.github.io/
baseurl: ""
paginate_path: "page:num/"
permalink: ":year/:month/:day/:title"

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

#sass:
  #sass_dir:     _sass
  
navigation:
  - title: Home
    url: /index.html
  - title: About
    url: /about
  #- title: Contact
    #url: /contact

social:
  github: 
  twitter: 
  facebook: 
  email: 
  linkedin: 

google_analytics: "G-7272G8LZ1S"

disqus:
    shortname:
