title: Side Lower
description: Random Ramblings of SB

url: "https://sohamlive.github.io/"
baseurl: ""
paginate_path: "page:num/"
permalink: ":year/:month/:day/:title"

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate,jekyll-feed]
paginate: 5

#sass:
  #sass_dir:     _sass
  
navigation:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: About
    url: /about
  #- title: Contact
    #url: /contact

social:
  github: 
  twitter: 
  facebook: 
  email: 
  linkedin: 

google_analytics: "G-43M607NS9X"

disqus:
    shortname:
    

