title: Side Lower
description: The personal blog of SB
postdescription: Some writings here and there

url: "https://www.sidelower.in"
baseurl: ""
paginate_path: "page:num/"
permalink: ":year/:month/:day/:title"

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate,jekyll-feed,jekyll-sitemap]
paginate: 5

#sass:
  #sass_dir:     _sass
  
navigation:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  - title: About
    url: /about
  #- title: Contact
    #url: /contact

social:
  github: 
  twitter: 
  facebook: 
  email: 
  linkedin: 

google_analytics: "G-N67YXBBYTB"

disqus:
    shortname:
    

